channels:
- conda-forge
- cerebis
- pytorch
dependencies:
- python=3.7
- pip=21.3.1
- numpy~=1.21.6
- libffi=3.3
- pycocotools=2.0.2
- shap=0.39.0
- recordclass=0.14.3
- llvmlite=0.36.0
- pip:
  - azureml-core==1.46.0
  - azureml-mlflow==1.46.0
  - azureml-dataset-runtime==1.46.0
  - azureml-telemetry==1.46.0
  - azureml-responsibleai==1.46.0
  - azureml-automl-core==1.46.1.post1
  - azureml-automl-runtime==1.46.1.post1
  - azureml-train-automl-client==1.46.0
  - azureml-defaults==1.46.0
  - azureml-interpret==1.46.0
  - azureml-train-automl-runtime==1.46.1.post1
  - azureml-automl-dnn-vision==1.46.1
  - azureml-dataprep>=2.24.4
name: project_environment
